# What is Numpy?

### Numpy is a python library that provides to mathematical tools such as MATLAB and R. While numpy significantly simplifies the user experience, if also offers comprehensive mathematical functions.

# What is Pandas?

### Pandas is an extremely popular Python library for data analysis and manipulation.

### Data exploration and data analysis is typically an iterative process, in which the data scientist takes a sample of data and performs the following kinds of tasks to analyze it and test hypothesis.

<ol>
<li> <strong>Clean Data</strong> to handle errors, missing values and other issues. </li>
<li><strong>Apply statistical techniques to better understand the data</strong> and how the sample might be expected to represent the real-world population of data, allowing for random variation.</li>
<li><strong>Visualize data</strong> to determine relationships between variables and in the case of a machine learning project identify features that are potentially predictive of the labels.</li>
<li><strong>Revise the hypothesis</strong> and repeat the process.</li>
</ol>

In [1]:
### Numpy arrays

data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
print(data)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]

In [ ]:
import numpy as np

grades = np.array(data)
print(grades)

print(type(data), 'x 2', data * 2)

print('------')

print(type(grades), 'x 2', grades * 2)

[50 50 47 97 49  3 53 42 26 74 82 62 37 15 70 27 36 35 48 52 63 64]
<class 'list'> x 2 [50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64, 50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]
------
<class 'numpy.ndarray'> x 2 [100 100  94 194  98   6 106  84  52 148 164 124  74  30 140  54  72  70
  96 104 126 128]

np.float64(49.18181818181818)

In [6]:
print(grades.shape)

print(grades[0])

print(grades.mean())

(22,)
50
49.18181818181818

In [7]:
# Define an array of study hours
study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]


# Create a 2D array (an array of arrays)
student_data = np.array([study_hours, grades])


# display the array
student_data

array([[10.  , 11.5 ,  9.  , 16.  ,  9.25,  1.  , 11.5 ,  9.  ,  8.5 ,
        14.5 , 15.5 , 13.75,  9.  ,  8.  , 15.5 ,  8.  ,  9.  ,  6.  ,
        10.  , 12.  , 12.5 , 12.  ],
       [50.  , 50.  , 47.  , 97.  , 49.  ,  3.  , 53.  , 42.  , 26.  ,
        74.  , 82.  , 62.  , 37.  , 15.  , 70.  , 27.  , 36.  , 35.  ,
        48.  , 52.  , 63.  , 64.  ]])

In [10]:
print(student_data.shape)

print(student_data[0][0])

avg_study = student_data[0].mean()

avg_grade = student_data[1].mean()

print(f'Average study hours: { avg_study } \nAverage grade: { avg_grade }')

(2, 22)
10.0
Average study hours: 10.522727272727273
Average grade: 49.18181818181818

In [11]:
### Exploring tabular data with Pandas 

import pandas as pd

df_students = pd.DataFrame({'Name': ['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie', 'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny', 'Jakeem','Helena','Ismat','Anila','Skye','Daniel','Aisha'], 
                            'StudyHours': study_hours, 
                            'Grade': grades})


df_students

         Name  StudyHours  Grade
0         Dan       10.00     50
1       Joann       11.50     50
2       Pedro        9.00     47
3       Rosie       16.00     97
4       Ethan        9.25     49
5       Vicky        1.00      3
6    Frederic       11.50     53
7      Jimmie        9.00     42
8      Rhonda        8.50     26
9    Giovanni       14.50     74
10  Francesca       15.50     82
11      Rajab       13.75     62
12    Naiyana        9.00     37
13       Kian        8.00     15
14      Jenny       15.50     70
15     Jakeem        8.00     27
16     Helena        9.00     36
17      Ismat        6.00     35
18      Anila       10.00     48
19       Skye       12.00     52
20     Daniel       12.50     63
21      Aisha       12.00     64

In [20]:
# Finding and filtering data in DataFrames

print(df_students.loc[5])

print(df_students.loc[0:5])

print(df_students.iloc[0:5])

print(df_students.iloc[0, [1,2]])

print(df_students.loc[0, 'Grade'])

print(df_students.loc[df_students['Name'] == 'Aisha'])

print(df_students[df_students['Name'] == 'Aisha'])

print(df_students.query("Name == 'Aisha'"))

Name          Vicky
StudyHours      1.0
Grade             3
Name: 5, dtype: object
    Name  StudyHours  Grade
0    Dan       10.00     50
1  Joann       11.50     50
2  Pedro        9.00     47
3  Rosie       16.00     97
4  Ethan        9.25     49
5  Vicky        1.00      3
    Name  StudyHours  Grade
0    Dan       10.00     50
1  Joann       11.50     50
2  Pedro        9.00     47
3  Rosie       16.00     97
4  Ethan        9.25     49
StudyHours    10.0
Grade           50
Name: 0, dtype: object
50
     Name  StudyHours  Grade
21  Aisha        12.0     64
     Name  StudyHours  Grade
21  Aisha        12.0     64
     Name  StudyHours  Grade
21  Aisha        12.0     64

In [22]:
# Handling missing values 

print(df_students.isnull())

print(df_students.isnull().sum())

df_students[df_students.isnull().any(axis=1)]

     Name  StudyHours  Grade
0   False       False  False
1   False       False  False
2   False       False  False
3   False       False  False
4   False       False  False
5   False       False  False
6   False       False  False
7   False       False  False
8   False       False  False
9   False       False  False
10  False       False  False
11  False       False  False
12  False       False  False
13  False       False  False
14  False       False  False
15  False       False  False
16  False       False  False
17  False       False  False
18  False       False  False
19  False       False  False
20  False       False  False
21  False       False  False
Name          0
StudyHours    0
Grade         0
dtype: int64

Empty DataFrame
Columns: [Name, StudyHours, Grade]
Index: []

In [23]:
df_students.StudyHours = df_students.StudyHours.fillna(df_students.StudyHours.mean())

df_students

         Name  StudyHours  Grade
0         Dan       10.00     50
1       Joann       11.50     50
2       Pedro        9.00     47
3       Rosie       16.00     97
4       Ethan        9.25     49
5       Vicky        1.00      3
6    Frederic       11.50     53
7      Jimmie        9.00     42
8      Rhonda        8.50     26
9    Giovanni       14.50     74
10  Francesca       15.50     82
11      Rajab       13.75     62
12    Naiyana        9.00     37
13       Kian        8.00     15
14      Jenny       15.50     70
15     Jakeem        8.00     27
16     Helena        9.00     36
17      Ismat        6.00     35
18      Anila       10.00     48
19       Skye       12.00     52
20     Daniel       12.50     63
21      Aisha       12.00     64

In [24]:
df_students = df_students.dropna(axis=0, how='any')
df_students

         Name  StudyHours  Grade
0         Dan       10.00     50
1       Joann       11.50     50
2       Pedro        9.00     47
3       Rosie       16.00     97
4       Ethan        9.25     49
5       Vicky        1.00      3
6    Frederic       11.50     53
7      Jimmie        9.00     42
8      Rhonda        8.50     26
9    Giovanni       14.50     74
10  Francesca       15.50     82
11      Rajab       13.75     62
12    Naiyana        9.00     37
13       Kian        8.00     15
14      Jenny       15.50     70
15     Jakeem        8.00     27
16     Helena        9.00     36
17      Ismat        6.00     35
18      Anila       10.00     48
19       Skye       12.00     52
20     Daniel       12.50     63
21      Aisha       12.00     64

In [25]:
# Explore data in the DataFrame

mean_study = df_students['StudyHours'].mean()

mean_grade = df_students['Grade'].mean()

print(f'Average study hours: { mean_study } \nAverage grade: { mean_grade }')

Average study hours: 10.522727272727273
Average grade: 49.18181818181818

In [27]:
print(df_students[df_students.StudyHours > mean_study])

print(df_students[df_students.Grade > mean_grade].Grade.mean())

         Name  StudyHours  Grade
1       Joann       11.50     50
3       Rosie       16.00     97
6    Frederic       11.50     53
9    Giovanni       14.50     74
10  Francesca       15.50     82
11      Rajab       13.75     62
14      Jenny       15.50     70
19       Skye       12.00     52
20     Daniel       12.50     63
21      Aisha       12.00     64
65.18181818181819

In [28]:
passes = pd.Series(df_students.Grade >= 60)

df_students = pd.concat([df_students, passes.rename('Pass')], axis=1)

df_students

         Name  StudyHours  Grade   Pass
0         Dan       10.00     50  False
1       Joann       11.50     50  False
2       Pedro        9.00     47  False
3       Rosie       16.00     97   True
4       Ethan        9.25     49  False
5       Vicky        1.00      3  False
6    Frederic       11.50     53  False
7      Jimmie        9.00     42  False
8      Rhonda        8.50     26  False
9    Giovanni       14.50     74   True
10  Francesca       15.50     82   True
11      Rajab       13.75     62   True
12    Naiyana        9.00     37  False
13       Kian        8.00     15  False
14      Jenny       15.50     70   True
15     Jakeem        8.00     27  False
16     Helena        9.00     36  False
17      Ismat        6.00     35  False
18      Anila       10.00     48  False
19       Skye       12.00     52  False
20     Daniel       12.50     63   True
21      Aisha       12.00     64   True

In [29]:
df_students = df_students.sort_values(by='Grade', ascending=False)
df_students

         Name  StudyHours  Grade   Pass
3       Rosie       16.00     97   True
10  Francesca       15.50     82   True
9    Giovanni       14.50     74   True
14      Jenny       15.50     70   True
21      Aisha       12.00     64   True
20     Daniel       12.50     63   True
11      Rajab       13.75     62   True
6    Frederic       11.50     53  False
19       Skye       12.00     52  False
1       Joann       11.50     50  False
0         Dan       10.00     50  False
4       Ethan        9.25     49  False
18      Anila       10.00     48  False
2       Pedro        9.00     47  False
7      Jimmie        9.00     42  False
12    Naiyana        9.00     37  False
16     Helena        9.00     36  False
17      Ismat        6.00     35  False
15     Jakeem        8.00     27  False
8      Rhonda        8.50     26  False
13       Kian        8.00     15  False
5       Vicky        1.00      3  False